name: Test Feature

on:
  push:
    branches: [ 'feature/**' ]
  pull_request:
    branches: [ 'feature/**' ]

jobs:

  build-test-feature:
    runs-on: [ self-hosted, linux, x64, earable-backend ]
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        export APP_NAME="<< TO DO >>"
        docker build -f Dockerfile.test .
